### ISSUE TITLE
How to align multiples timeseries without a reference

### ISSUE THREAD

**Issue by CNelias** [yu-lab-vt/BILCO#1]
The original GTW paper states that it can be used to ```jointly``` align multiple timeseries, which what I am trying to do. 
In the paper, it is said that using a reference series to align others is just a *special case* of GTW, optimizing each series yn with respect to "x1 = x2 = · · · = xN = x". 
When I look at the provided demo.m and the corresponding functions, it seems that ```BILCO.m``` *requires* a reference, at least in the matlab version of the code:
```
function [minCut,maxFlow] = BILCO(ref,tst,Gij,smo,initialCut,winSize,metric)
```
This would defeat the purpose of the whole algorithm, making it not a special case but a mandatory requirement. 

I do not have a reference series, but am trying to jointly align several series. Is there a way to do that with the current BILCO implementation? If so, how can I do that? It is not clear from the demo how to proceed.

**Comment by XuelongMi** [comment]
GTW is designed to align multiple **pairs** of time series jointly. That means each time series should have one corresponding reference, it is a mandatory requirement. In our example, we usually set the reference for all the pairs to be the same to achieve the goal for multiple time series alignment. The "demo.m" only demonstrates how to use BILCO to perform such joint alignment. **Obtaining reference can be seen as one preprocessing step for BILCO.**
If you do not have one reference series and you can assume time series to be aligned are similar but only with delay, you can pick one representative time series out (such as the one with the highest SNR or by averaging some series), denoise it, then use it as reference series. 
Alternatively, if you know the model of the series (for example, it should only increase to a peak and then decrease to the baseline), then you can also generate such a curve with the same length as the reference (for example, using a triangle shape as the reference, then the alignment will align such triangle shape to the signal).

After you have chosen the reference, you need to scale the reference to be within the same value range of the test series of the same pair before performing the alignment. For example, if there are N pairs of time series (x_1,y_1),...,(x_N,y_N) to be aligned, where {y} are the time series to be aligned, {x} should represent the reference of each pair and you don't have, you choose x_ref as the reference through above ways, then you can obtain x_1 by scaling x_ref to be within the same value range of y_1. Similarly, you can obtain all {x} then do the alignment. In the paper, I assume all the series are with the same value range, thus x_1 = x_2 = ... = x_N = x_ref.

**Comment by CNelias** [comment]
I see. Thanks for the detailed infos. I am not sure I can use this method then... I'll have to think about how to come up with a reasonnable reference.
